version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels: []
    schedule:
      interval: "weekly"
    target-branch: "main"
    cooldown:
      default-days: 7
    groups:
      actions:
        patterns:
          - "*"
