#!/bin/bash

rm -rf \
  node_modules/ \
  dist/ \
  yarn-error.log \
  .yarn/cache \
  .yarn/install-state.gz \
  coverage \
  .pnp.* \
  openapi.yaml \
  demo/public/mockServiceWorker.js \
  build \
