import type { FC } from "react";
import { Notification } from "@canonical/react-components";
import { useSettings } from "context/useSettings";
import { useNavigate } from "react-router-dom";
import { ROOT_PATH } from "util/rootPath";
import { useAuth } from "context/auth";
import { AUTH_METHOD } from "util/authentication";

const CertificateAddNotifications: FC = () => {
  const { data: settings } = useSettings();
  const { authMethod } = useAuth();
  const hasCertificate = settings?.client_certificate;
  const isBearerToken = authMethod === AUTH_METHOD.BEARER;
  const navigate = useNavigate();

  return (
    <>
      {!isBearerToken && (
        <Notification title="Identity trust token" severity="information">
          In order for your browser certificate to be added to the
          server&rsquo;s trust store, you must present an identity trust token
          generated by the server.
        </Notification>
      )}
      {isBearerToken && (
        <Notification title="TLS identity" severity="information">
          Confirm the name and auth groups for your permanent access.
        </Notification>
      )}
      {hasCertificate === false && (
        <Notification
          severity="caution"
          title="Missing client certificate"
          actions={[
            {
              label: "Go back to step 1",
              onClick: () => {
                navigate(`${ROOT_PATH}/ui/login/certificate-generate`);
              },
            },
          ]}
        >
          You are missing an installed client certificate. You may not be able
          to authenticate.
        </Notification>
      )}
    </>
  );
};

export default CertificateAddNotifications;
