export const queryKeys = {
  certificates: "certificates",
  cluster: "cluster",
  images: "images",
  instances: "instances",
  logs: "logs",
  members: "members",
  metrics: "metrics",
  networks: "networks",
  profiles: "profiles",
  projects: "projects",
  resources: "resources",
  storage: "storage",
  settings: "settings",
  warnings: "warnings",
};
