name: Vulnerability Scanning with Trivy
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Test Trivy daily at midnight

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  trivy-repo:
    name: Trivy vulnerability scanner - Repository
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      security-events: write # for uploading SARIF results to the security tab
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: main
          persist-credentials: false

      - name: Create Trivy cache directory
        run: mkdir -p /home/runner/vuln-cache

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          scan-type: "fs"
          format: "sarif"
          output: "trivy-lxd-repo-scan-results.sarif"
          cache-dir: "/home/runner/vuln-cache"
          severity: "LOW,MEDIUM,HIGH,CRITICAL"

      - name: Cache trivy and vulnerability database
        uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: /home/runner/vuln-cache
          key: trivy-cache

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@87557b9c84dde89fdd9b10e88954ac2f4248e463 # v4.36.1
        with:
          sarif_file: "trivy-lxd-repo-scan-results.sarif"
          sha: ${{ github.sha }}
          ref: refs/heads/main