name: Demo update
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  updateBranch:
    name: Update demo branch
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{ github.repository_owner == 'canonical' }}
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: true # zizmor: ignore[artipacked]
    - name: Fetch rebase and push
      if: github.ref == 'refs/heads/main'
      run: |
        git config --global user.email "github-action@example.com"
        git config --global user.name "GitHub Action"
        git branch demo
        git checkout demo
        touch wip-file
        git add wip-file
        git commit -am "wip"
        git push origin demo --force
