name: Demo update
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  updateBranch:
    name: Update demo branch
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'canonical' }}
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: true # zizmor: ignore[artipacked]
    - name: Fetch rebase and push
      if: github.ref == 'refs/heads/main'
      run: |
        git config --global user.email "github-action@example.com"
        git config --global user.name "GitHub Action"
        git branch demo
        git checkout demo
        touch wip-file
        git add wip-file
        git commit -am "wip"
        git push origin demo --force
