#! /usr/bin/env bash
set -e

# create oidc user foo
lxd sql global "
    INSERT OR REPLACE INTO identities 
    (id, auth_method, type, identifier, name, metadata) 
    VALUES 
    (
        (SELECT id from identities WHERE name='foo'),
        2, 
        5, 
        'foo@foo.com', 
        'foo', 
        '{}'
    );
"

# create oidc user bar
lxd sql global "
    INSERT OR REPLACE INTO identities 
    (id, auth_method, type, identifier, name, metadata) 
    VALUES 
    (
        (SELECT id from identities WHERE name='bar'),
        2, 
        5, 
        'bar@bar.com', 
        'bar', 
        '{}'
    );
"
