#! /usr/bin/env bash
set -e

LXC_CMD="sudo lxc"
LXD_CMD="sudo lxd"
SNAP_CMD="sudo snap"
if [ "$DEPLOYMENT" = "clustered" ]; then
    echo "Configuring clustered environment via vm1..."
    LXC_CMD="sudo lxc exec vm1 -- lxc"
    LXD_CMD="sudo lxc exec vm1 -- lxd"
    SNAP_CMD="sudo lxc exec vm1 -- snap"
fi

# hasNeededAPIExtension: check if LXD supports the needed extension.
hasNeededAPIExtension() (
    needed_extension="${1}"
    $LXC_CMD info | grep -qxFm1 -- "- ${needed_extension}"
)

if [ -f .env.local ]
then
  set -o allexport; source .env.local; set +o allexport
fi

# Apply OIDC settings
$LXC_CMD config set oidc.issuer "${LXD_OIDC_ISSUER}"
$LXC_CMD config set oidc.client.id "${LXD_OIDC_CLIENT_ID}"
$LXC_CMD config set oidc.audience "${LXD_OIDC_AUDIENCE}"
$LXC_CMD config set oidc.groups.claim "${LXD_OIDC_GROUPS_CLAIM}"

# Logic for Secret (Only if the extension exists)
if hasNeededAPIExtension "oidc_client_secret"; then
    $LXC_CMD config set oidc.client.secret=${LXD_OIDC_CLIENT_SECRET}
    echo "OIDC client secret is set."
fi

# Auth groups
$LXC_CMD auth group create login-admin
$LXC_CMD auth group permission add login-admin server admin
$LXC_CMD auth identity-provider-group create admin
$LXC_CMD auth identity-provider-group group add admin login-admin

# SQL - Ensure we don't fail if the user already exists
$LXD_CMD sql global "INSERT OR REPLACE INTO identities (auth_method, type, identifier, name, metadata) VALUES (2, 5, 'foo@foo.com', 'foo', '{}');"
$LXD_CMD sql global "INSERT OR REPLACE INTO identities (auth_method, type, identifier, name, metadata) VALUES (2, 5, 'bar@bar.com', 'bar', '{}');"

