#! /usr/bin/env bash
set -e

lxd sql global "
    DELETE
    FROM identities
    WHERE name IN ('foo', 'bar', 'admin');
"
lxc auth identity-provider-group delete admin
lxc auth group delete login-admin
